pythonProject/admin/routes.py
from flask import Blueprint
from flask import render_template, request, session, redirect, flash, url_for
from pythonProject.models import emp_details
from pythonProject import db, params
from pythonProject.user.forms import RegistrationForm

admin = Blueprint('admin', __name__)


@admin.route("/admin_login", methods=['GET', 'POST'])
def admin_login():
    form = RegistrationForm()
    if 'user' in session and session['user'] == params['admin_user']:
        page = request.args.get('page', 1, type=int)
        emps = emp_details.query.paginate(page=page, per_page=params['ROWS_PER_PAGE'], error_out=False)
        return render_template('index.html', params=params, emps=emps,form=form)

    if request.method == 'POST':
        username = request.form.get('uname')
        userpass = request.form.get('pass')
        if username == params['admin_user'] and userpass == params['admin_password']:
            # set the session variable
            session['user'] = username
            return redirect(url_for('admin.dashboard'))

        else:
            flash("Enter correct credentials")
            return render_template('admin_login.html', params=params)

    else:
        return render_template('admin_login.html', params=params)


@admin.route("/dashboard", methods=['GET', 'POST'])
def dashboard():
    form = RegistrationForm()
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search = "%{}%".format(tag)
        page = request.args.get('page', 1, type=int)
        emps = emp_details.query.filter(emp_details.firstName.like(search)).paginate(page=page,
                                                                                     per_page=params['ROWS_PER_PAGE'],
                                                                                     error_out=False)
        return render_template('index.html', params=params, emps=emps, form=form)
    else:
        page = request.args.get('page', 1, type=int)
        emps = emp_details.query.paginate(page=page, per_page=params['ROWS_PER_PAGE'],
                                          error_out=False)
        return render_template('index.html', params=params, emps=emps, form=form)


@admin.route("/add_employee", methods=['GET', 'POST'])
def add_employee():
    form = RegistrationForm()
    if form.validate_on_submit():
        '''Add Entry to the Database'''
        fname = form.firstName.data
        lname = form.lastName.data
        email = form.email.data
        phone = form.phone.data
        dob = form.dob.data
        address = form.address.data
        password = form.password.data

        entry = emp_details(firstName=fname, lastName=lname, phone=phone, address=address, email=email, dob=dob,
                            password=password)
        db.session.add(entry)
        db.session.commit()
        return redirect(url_for('admin.dashboard'))

    emps = emp_details.query.all()
    return render_template('index.html', params=params, emps=emps, form=form)


@admin.route("/delete/<string:sno>", methods=['GET', 'POST'])
def delete(sno):
    if 'user' in session and session['user'] == params['admin_user']:
        post = emp_details.query.filter_by(id=sno).first()
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('admin.admin_login'))


@admin.route("/logout")
def logout():
    session.pop('user')
    session.clear()
    return redirect(url_for('admin.admin_login'))

pythonProject/user/routes.py
from flask import Blueprint
from flask import render_template, request, session, redirect, flash, url_for
from flask_login import login_user, current_user, logout_user
from pythonProject.models import emp_details
from pythonProject import params, db
from pythonProject.user.forms import RegistrationForm, LoginForm


users = Blueprint('users', __name__)


@users.route("/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        emp = emp_details.query.filter_by(id=current_user.id).first()
        other_emp = emp_details.query.all()
        return render_template('profile.html', emp=emp, other_emp=other_emp)
    if form.validate_on_submit():
        user = emp_details.query.filter_by(email=form.emailID.data).first()
        if user and user.password == form.password.data:
            login_user(user)
            emp = emp_details.query.filter_by(email=user.email).first()
            return redirect(url_for('users.profile', sno=emp.id))
        else:
            flash('Invalid username or Password', 'warning')
    return render_template('login.html', form=form)


@users.route("/logout_emp")
def logout_emp():
    logout_user()
    return redirect('/')


@users.route("/edit/<string:sno>/<string:flag>", methods=['GET', 'POST'])
def edit(sno, flag):
    emp = emp_details.query.filter_by(id=sno).first()
    if current_user.is_authenticated or ('user' in session and session['user'] == params['admin_user']):
        if request.method == 'POST':
            fname = request.form.get('firstName')
            lname = request.form.get('lastName')
            email = request.form.get('email')
            phone = request.form.get('phone')
            address = request.form.get('address')
            dob = request.form.get('DOB')
            password = request.form.get('password')
            cpassword = request.form.get('cpassword')
            emp = emp_details.query.filter_by(id=sno).first()
            if emp.email == email or (emp_details.query.filter_by(email=email).first() is None):
                emp.firstName = fname
                emp.lastName = lname
                emp.email = email
                emp.phone = phone
                emp.address = address
                emp.dob = dob
                emp.password = password
                db.session.commit()
                # return redirect('user./edit/' + sno + '/' + flag)
                return redirect(url_for('users.edit', sno=emp.id, flag=flag))
            else:
                flash('This email id is already registered', 'danger')
        emp = emp_details.query.filter_by(id=sno).first()
        return render_template('edit.html', params=params, emp=emp, id=sno, flag=flag)
    else:
        return redirect(url_for('users.login'))


@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        '''Add Entry to the Database'''
        fname = form.firstName.data
        lname = form.lastName.data
        email = form.email.data
        phone = form.phone.data
        dob = form.dob.data
        address = form.address.data
        password = form.password.data

        entry = emp_details(firstName=fname, lastName=lname, phone=phone, address=address, email=email, dob=dob,
                            password=password)
        db.session.add(entry)
        db.session.commit()
        # flash('Successfully Registered', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form, params=params)


@users.route("/profile/<string:sno>")
def profile(sno):
    if current_user.is_authenticated:
        emp = emp_details.query.filter_by(id=sno).first()
        other_emp = emp_details.query.all()
        return render_template('profile.html', params=params, emp=emp, other_emp=other_emp)
    else:
        return redirect(url_for('users.login'))

pythonProject/templates/admin_login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>ADMIN LOGIN</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link href="{{url_for('static', filename='css/admin_login.css')}}" rel="stylesheet">
<link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body style="background-image: url('{{ url_for('static',filename = 'img/admin.jpg') }}')">
<!-- partial:index.partial.html -->
<div class="log-form">
  <h2 style="color: #ffffff">ADMIN LOGIN</h2>
  <form action="{{url_for('admin.admin_login')}}" method="post">
    <label for="uname">Username</label>
    <input type="text" id="uname" name="uname"  required autofocus>
    <label for="pass">Password</label>
    <input type="password" id="pass" name="pass"  required>

    <!-- <input type="text" title="username" placeholder="username" /> -->
    <!-- <input type="password" title="username" placeholder="password" /> -->
    {% with messages = get_flashed_messages()  %}
       
                                    
                                      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissible fade show  " role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

    <button type="submit" class="btn btn-primary">Login</button>
    <a href="{{url_for('users.login')}}"><button type="button" class="btn btn-primary">Homepage</button></a>
  </form>
</div>

  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
</body>
</html>

pythonProject/templates/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Dashboard</title>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto|Varela+Round'>
<link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
<link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
<!-- <link href="{{url_for('static', filename='css/register.css')}}" rel="stylesheet"> -->
    <script src="{{url_for('static', filename='js/validation.js')}}"></script>

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
  <div class="table-wrapper">
    <div class="table-title">
      <form method="post" action="/dashboard" >
      <div class="row">
        <div class="col-md-3">
          <h2>Manage <b>Employees</b></h2>
        </div>
        <div class="form-group col-md-9">
          <div class="col col-md-6">
            
          <input type="text" name="tag" id="tag" class="form-control" placeholder="Enter Keyword">

          </div>
          <div class="col col-md-6">
            
          <a href="{{url_for('admin.logout')}}" class="btn btn-danger"><i class="material-icons">logout</i> <span>Logout</span></a>
          <a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Employee</span></a>

          <input type="submit" value="Search" name="Search" class="btn btn-primary" style="height: 33px;">
          </div>
          
        </div>
      </div>
      </form>
    </div>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Date-Of-Birth</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {%for emp in emps.items%}
        <tr>
          <td>{{emp.firstName}} {{emp.lastName}}</td>
          <td>{{emp.email}}</td>
          <td>{{emp.address}}</td>
          <td>{{emp.phone}}</td>
          <td>{{emp.dob}}</td>
          <td>
            <a href="{{ url_for('users.edit',sno = emp.id, flag = 1) }}"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
            <a href="{{ url_for('admin.delete',sno = emp.id) }}"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="text-right">
    <a href="{{ url_for('admin.admin_login', page=emps.prev_num) }}"
       class="btn btn-outline-dark 
       {% if emps.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
    <!-- Loop through the number of pages to display a link for each-->
    
    <a href="{{ url_for('admin.admin_login', page=emps.next_num) }}"
       class="btn btn-outline-dark 
       {% if emps.page == emps.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-right mt-3">
   Showing page {{ emps.page }} of {{ emps.pages }}
</p>
  </div>
</div>
<!-- add Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="{{url_for('admin.add_employee')}}" method="post">
        <div class="modal-header">
          <h4 class="modal-title">Add Employee</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          {{ form.hidden_tag() }}
          <div class="form-group">
              {{ form.firstName.label(class="form-control-label") }}

              {% if form.firstName.errors %}
                  {{ form.firstName(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.firstName.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.firstName(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.lastName.label(class="form-control-label") }}

              {% if form.lastName.errors %}
                  {{ form.lastName(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.lastName.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.lastName(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.email.label(class="form-control-label") }}

              {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.phone.label(class="form-control-label") }}

              {% if form.phone.errors %}
                  {{ form.phone(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.phone.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.phone(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.dob.label(class="form-control-label") }}

              {% if form.dob.errors %}
                  {{ form.dob(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.dob.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.dob(class="form-control form-control-lg") }}
              {% endif %}
          </div>


          <div class="form-group">
              {{ form.address.label(class="form-control-label") }}

              {% if form.address.errors %}
                  {{ form.address(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.address.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.address(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.password.label(class="form-control-label") }}
              {% if form.password.errors %}
                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.password(class="form-control form-control-lg") }}
              {% endif %}
          </div>

          <div class="form-group">
              {{ form.confirm_password.label(class="form-control-label") }}
              {% if form.confirm_password.errors %}
                  {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.confirm_password(class="form-control form-control-lg") }}
              {% endif %}
          </div>
        </div>
        
        <div class="modal-footer">

          <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
          <input type="submit" class="btn btn-success" value="Add">
        </div>
      </form>
    </div>
  </div>
</div>

<!-- partial -->
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

</body>
</html>

pythonProject/templates/login.html
{%import "bootstrap/wtf.html" as wtf%}
<!DOCTYPE html>
<html>
<head>
	<title>LOGIN</title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
	<link href="{{url_for('static', filename='css/login.css')}}" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
</head>
<body style="background-image: url('{{ url_for('static',filename = 'img/login3.jpg') }}')">
	<div class="sidenav" style="background-image: url('{{ url_for('static',filename = 'img/bg.jpg') }}')">
         <div class="login-main-text">
            <h2>Employee Management App<br> Login Page</h2>
            <p>Login or register from here to access.</p>
         </div>
  </div>
      <div class="main" >

         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form method="POST" action="{{url_for('users.login')}}" style="color: #ffffff">
               		{{ form.hidden_tag() }}
               		{{ wtf.form_field(form.emailID) }}
        			    {{ wtf.form_field(form.password) }}
                  {% with messages = get_flashed_messages()  %}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                      </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                  {% endwith %}
                  <button type="submit" class="btn btn-primary">Login</button>
                  <a href="{{url_for('admin.admin_login')}}"><button type="button" class="btn btn-black">Admin Login</button></a>
                  <a href="{{url_for('users.register')}}"><button type="button" class="btn btn-black">Register</button></a>
               </form>
            </div>
         </div>
      </div>

</body>
</html>

pythonProject/templates/profile.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Profile</title>
<link href="http://netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<link href="{{url_for('static', filename='css/profile.css')}}" rel="stylesheet">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{url_for('static', filename='img/user.png')}}" width="150" height="150">
                    <div class="mt-3">
                      <h4>{{emp.firstName}} {{emp.lastName}}</h4>
                      <p class="text-secondary mb-1">{{emp.email}}</p>
                      <p class="text-muted font-size-sm">{{emp.phone}}</p>
                      <a href="{{ url_for('users.edit',sno = emp.id, flag = 0) }}"><button class="btn btn-primary">Update</button></a>
                      <a href="{{ url_for('users.logout_emp') }}"><button type="button" class="btn btn-outline-primary">Logout</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8" >
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.firstName}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.lastName}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.email}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.phone}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.address}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Date-Of-Birth</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{emp.dob}}
                    </div>
                  </div>
                </div>
              </div>
          	</div>
          	<div class="col-md-12">
          		
          	<h1>Other Employees</h1>
          	</div>
          	<div class="col-md-12" style="overflow:auto; height:400px;">
              <div class="card mb-3">
                	{% for x in other_emp %}
                <div class="card-body">
                  <div class="row" style="text-align: center;">
                    <div class="col-sm-4">
                      <h6 class="mb-0">{{x.firstName}} {{x.lastName}}</h6>
                    </div>
                    <div class="col-sm-8 text-secondary">
                      {{x.email}}
                    </div>
                  </div>
                </div>
                  <hr>
                  {% endfor %}
              </div>
            </div>
          </div>
        </div>
    </div>
<!-- partial -->
  
</body>
</html>